export const courses = [
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Civil',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Mechanical',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Electrical',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Electronics',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Computer Engineering',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'IT',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Automobile',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Chemical',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Poly Dip',
        name: 'Polytechnic Diploma',
        specialization: 'Mining',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'CSE',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'IT',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'Mechanical',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'Civil',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'ECE',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Eng',
        name: 'Diploma in Engineering',
        specialization: 'Electrical',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'D.Pharm',
        name: 'Diploma in Pharmacy',
        specialization: 'Pharmacy',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Nursing',
        name: 'Diploma in Nursing',
        specialization: 'General Nursing',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'D.El.Ed',
        name: 'Diploma in Education',
        specialization: 'Elementary Education',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'DHM',
        name: 'Diploma in Hotel Management',
        specialization: 'Hotel Operations',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'DHM',
        name: 'Diploma in Hotel Management',
        specialization: 'Hospitality',
        duration: 36,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Agri',
        name: 'Diploma in Agriculture',
        specialization: 'Agriculture',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'DFD',
        name: 'Diploma in Fashion Design',
        specialization: 'Fashion Design',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'DID',
        name: 'Diploma in Interior Design',
        specialization: 'Interior Design',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Anim',
        name: 'Diploma in Animation',
        specialization: 'Animation',
        duration: 24,
    },
    {
        level: 'Diploma',
        shortName: 'Dip Anim',
        name: 'Diploma in Animation',
        specialization: 'VFX',
        duration: 24,
    },
    {
        level: 'Advanced Diploma',
        shortName: 'Adv Dip',
        name: 'Advanced Diploma',
        specialization: 'Computer Science',
        duration: 24,
    },
    {
        level: 'Advanced Diploma',
        shortName: 'Adv Dip',
        name: 'Advanced Diploma',
        specialization: 'Networking',
        duration: 24,
    },
    {
        level: 'Advanced Diploma',
        shortName: 'Adv Dip',
        name: 'Advanced Diploma',
        specialization: 'AI',
        duration: 24,
    },
    {
        level: 'Advanced Diploma',
        shortName: 'Adv Dip',
        name: 'Advanced Diploma',
        specialization: 'Cyber Security',
        duration: 24,
    },
    {
        level: 'Advanced Diploma',
        shortName: 'Adv Dip',
        name: 'Advanced Diploma',
        specialization: 'Business Management',
        duration: 24,
    },

    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Computer Science (CSE)',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'AI & ML',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Data Science',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Cyber Security',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Information Technology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Electronics & Communication (ECE)',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Electrical (EEE)',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Mechanical',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Civil',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Chemical',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Biotechnology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Aerospace',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Mechatronics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Robotics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Automobile',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Petroleum',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Mining',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Textile',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Food Technology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Production',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Tech',
        name: 'Bachelor of Technology',
        specialization: 'Industrial Engineering',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'Computer Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'Software Development',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'Cloud Computing',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'AI',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'Data Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BCA',
        name: 'Bachelor of Computer Applications',
        specialization: 'Cyber Security',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Computer Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'IT',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Mathematics',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Physics',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Chemistry',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Statistics',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Biotechnology',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Microbiology',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Zoology',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Botany',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Environmental Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'Data Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc',
        name: 'Bachelor of Science',
        specialization: 'AI',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Computer Science',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'IT',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Mathematics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Physics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Chemistry',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Statistics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Biotechnology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Microbiology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Zoology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Botany',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Environmental Science',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'Data Science',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc (Hons)',
        name: 'Bachelor of Science (Honours)',
        specialization: 'AI',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'English',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Hindi',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'History',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Political Science',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Economics',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Sociology',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Psychology',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Geography',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Philosophy',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA',
        name: 'Bachelor of Arts',
        specialization: 'Journalism',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA (Hons)',
        name: 'Bachelor of Arts (Honours)',
        specialization: 'English',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BA (Hons)',
        name: 'Bachelor of Arts (Honours)',
        specialization: 'Economics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BA (Hons)',
        name: 'Bachelor of Arts (Honours)',
        specialization: 'Political Science',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BA (Hons)',
        name: 'Bachelor of Arts (Honours)',
        specialization: 'Psychology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BA (Hons)',
        name: 'Bachelor of Arts (Honours)',
        specialization: 'History',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com',
        name: 'Bachelor of Commerce',
        specialization: 'Accounting',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com',
        name: 'Bachelor of Commerce',
        specialization: 'Finance',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com',
        name: 'Bachelor of Commerce',
        specialization: 'Taxation',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com',
        name: 'Bachelor of Commerce',
        specialization: 'Banking',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com',
        name: 'Bachelor of Commerce',
        specialization: 'Insurance',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com (Hons)',
        name: 'Bachelor of Commerce (Honours)',
        specialization: 'Accounting',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com (Hons)',
        name: 'Bachelor of Commerce (Honours)',
        specialization: 'Finance',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com (Hons)',
        name: 'Bachelor of Commerce (Honours)',
        specialization: 'Economics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'Marketing',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'Finance',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'HR',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'Business Analytics',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'International Business',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'Entrepreneurship',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA',
        name: 'Bachelor of Business Administration',
        specialization: 'Digital Marketing',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BMS',
        name: 'Bachelor of Management Studies',
        specialization: 'Business Management',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BMS',
        name: 'Bachelor of Management Studies',
        specialization: 'Marketing',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BMS',
        name: 'Bachelor of Management Studies',
        specialization: 'Finance',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BSW',
        name: 'Bachelor of Social Work',
        specialization: 'Social Work',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Des',
        name: 'Bachelor of Design',
        specialization: 'Product Design',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Des',
        name: 'Bachelor of Design',
        specialization: 'UI/UX',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Des',
        name: 'Bachelor of Design',
        specialization: 'Fashion Design',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Des',
        name: 'Bachelor of Design',
        specialization: 'Interior Design',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Des',
        name: 'Bachelor of Design',
        specialization: 'Communication Design',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BFA',
        name: 'Bachelor of Fine Arts',
        specialization: 'Painting',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BFA',
        name: 'Bachelor of Fine Arts',
        specialization: 'Sculpture',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BFA',
        name: 'Bachelor of Fine Arts',
        specialization: 'Applied Arts',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BPA',
        name: 'Bachelor of Performing Arts',
        specialization: 'Music',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BPA',
        name: 'Bachelor of Performing Arts',
        specialization: 'Dance',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BPA',
        name: 'Bachelor of Performing Arts',
        specialization: 'Theatre',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BHM',
        name: 'Bachelor of Hotel Management',
        specialization: 'Hotel Management',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BHMCT',
        name: 'Bachelor of Hotel Management and Catering Technology',
        specialization: 'Hospitality & Catering',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Arch',
        name: 'Bachelor of Architecture',
        specialization: 'Architecture',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Plan',
        name: 'Bachelor of Planning',
        specialization: 'Urban Planning',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Pharm',
        name: 'Bachelor of Pharmacy',
        specialization: 'Pharmacy',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'Pharm.D',
        name: 'Doctor of Pharmacy',
        specialization: 'Clinical Pharmacy',
        duration: 72,
    },
    {
        level: "Bachelor's",
        shortName: 'BPT',
        name: 'Bachelor of Physiotherapy',
        specialization: 'Physiotherapy',
        duration: 54,
    },
    {
        level: "Bachelor's",
        shortName: 'BOT',
        name: 'Bachelor of Occupational Therapy',
        specialization: 'Occupational Therapy',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BASLP',
        name: 'Bachelor of Audiology and Speech-Language Pathology',
        specialization: 'Audiology & Speech Therapy',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Nursing',
        name: 'Bachelor of Science in Nursing',
        specialization: 'Nursing',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'MBBS',
        name: 'Bachelor of Medicine, Bachelor of Surgery',
        specialization: 'Medicine',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BDS',
        name: 'Bachelor of Dental Surgery',
        specialization: 'Dentistry',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'BAMS',
        name: 'Bachelor of Ayurvedic Medicine and Surgery',
        specialization: 'Ayurveda',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BHMS',
        name: 'Bachelor of Homeopathic Medicine and Surgery',
        specialization: 'Homeopathy',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BUMS',
        name: 'Bachelor of Unani Medicine and Surgery',
        specialization: 'Unani',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BSMS',
        name: 'Bachelor of Siddha Medicine and Surgery',
        specialization: 'Siddha',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BNYS',
        name: 'Bachelor of Naturopathy and Yogic Sciences',
        specialization: 'Naturopathy & Yoga',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'BVSc & AH',
        name: 'Bachelor of Veterinary Science and Animal Husbandry',
        specialization: 'Veterinary Science',
        duration: 66,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Agriculture',
        name: 'Bachelor of Science in Agriculture',
        specialization: 'Agronomy',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Agriculture',
        name: 'Bachelor of Science in Agriculture',
        specialization: 'Horticulture',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Agriculture',
        name: 'Bachelor of Science in Agriculture',
        specialization: 'Plant Pathology',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Agriculture',
        name: 'Bachelor of Science in Agriculture',
        specialization: 'Genetics',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Forestry',
        name: 'Bachelor of Science in Forestry',
        specialization: 'Forestry',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc Horticulture',
        name: 'Bachelor of Science in Horticulture',
        specialization: 'Horticulture',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'BFSc',
        name: 'Bachelor of Fisheries Science',
        specialization: 'Fisheries',
        duration: 48,
    },
    {
        level: "Bachelor's",
        shortName: 'LLB',
        name: 'Bachelor of Legislative Law',
        specialization: 'Law',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BA LLB',
        name: 'Bachelor of Arts and Bachelor of Legislative Law',
        specialization: 'Integrated Law',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'BBA LLB',
        name: 'Bachelor of Business Administration and Bachelor of Legislative Law',
        specialization: 'Business Law',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Com LLB',
        name: 'Bachelor of Commerce and Bachelor of Legislative Law',
        specialization: 'Corporate Law',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'B.Sc LLB',
        name: 'Bachelor of Science and Bachelor of Legislative Law',
        specialization: 'Science & Law',
        duration: 60,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Retail',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Automobile',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Software Development',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Healthcare',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Tourism',
        duration: 36,
    },
    {
        level: "Bachelor's",
        shortName: 'BVoc',
        name: 'Bachelor of Vocation',
        specialization: 'Logistics',
        duration: 36,
    },

    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'CSE',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'AI',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'ML',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Data Science',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Cyber Security',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Software Engineering',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Structural Engineering',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'VLSI',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Power Systems',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Tech',
        name: 'Master of Technology',
        specialization: 'Robotics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MCA',
        name: 'Master of Computer Applications',
        specialization: 'Computer Applications',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MCA',
        name: 'Master of Computer Applications',
        specialization: 'AI',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MCA',
        name: 'Master of Computer Applications',
        specialization: 'Cloud Computing',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MCA',
        name: 'Master of Computer Applications',
        specialization: 'Data Science',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Computer Science',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Mathematics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Physics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Chemistry',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Biotechnology',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Statistics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'AI',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSc',
        name: 'Master of Science',
        specialization: 'Data Science',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'English',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'Economics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'History',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'Political Science',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'Psychology',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MA',
        name: 'Master of Arts',
        specialization: 'Sociology',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Com',
        name: 'Master of Commerce',
        specialization: 'Finance',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Com',
        name: 'Master of Commerce',
        specialization: 'Accounting',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Com',
        name: 'Master of Commerce',
        specialization: 'Taxation',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Finance',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Marketing',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'HR',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Operations',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Business Analytics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'International Business',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Entrepreneurship',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'IT',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Healthcare',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MBA',
        name: 'Master of Business Administration',
        specialization: 'Supply Chain',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Des',
        name: 'Master of Design',
        specialization: 'Product Design',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Des',
        name: 'Master of Design',
        specialization: 'UX/UI',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Des',
        name: 'Master of Design',
        specialization: 'Fashion Design',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Arch',
        name: 'Master of Architecture',
        specialization: 'Architecture',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Plan',
        name: 'Master of Planning',
        specialization: 'Urban Planning',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Pharm',
        name: 'Master of Pharmacy',
        specialization: 'Pharmacology',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Pharm',
        name: 'Master of Pharmacy',
        specialization: 'Pharmaceutics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Pharm',
        name: 'Master of Pharmacy',
        specialization: 'Pharmaceutical Chemistry',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MPT',
        name: 'Master of Physiotherapy',
        specialization: 'Orthopedics',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MPT',
        name: 'Master of Physiotherapy',
        specialization: 'Neurology',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MPT',
        name: 'Master of Physiotherapy',
        specialization: 'Sports',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MSW',
        name: 'Master of Social Work',
        specialization: 'Social Work',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'M.Ed',
        name: 'Master of Education',
        specialization: 'Education',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'LLM',
        name: 'Master of Laws',
        specialization: 'Corporate Law',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'LLM',
        name: 'Master of Laws',
        specialization: 'Constitutional Law',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'LLM',
        name: 'Master of Laws',
        specialization: 'Criminal Law',
        duration: 24,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'General Medicine',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Pediatrics',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Radiology',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Dermatology',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Psychiatry',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Anaesthesia',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MD',
        name: 'Doctor of Medicine',
        specialization: 'Pathology',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MS',
        name: 'Master of Surgery',
        specialization: 'General Surgery',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MS',
        name: 'Master of Surgery',
        specialization: 'Orthopedics',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MS',
        name: 'Master of Surgery',
        specialization: 'ENT',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MS',
        name: 'Master of Surgery',
        specialization: 'Ophthalmology',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MS',
        name: 'Master of Surgery',
        specialization: 'Obstetrics & Gynaecology',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MDS',
        name: 'Master of Dental Surgery',
        specialization: 'Orthodontics',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MDS',
        name: 'Master of Dental Surgery',
        specialization: 'Oral Surgery',
        duration: 36,
    },
    {
        level: "Master's",
        shortName: 'MDS',
        name: 'Master of Dental Surgery',
        specialization: 'Prosthodontics',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Engineering',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Computer Science',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'AI',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Data Science',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Mathematics',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Physics',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Chemistry',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Biology',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Management',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Commerce',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Economics',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Psychology',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Law',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Education',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Agriculture',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'PhD',
        name: 'Doctor of Philosophy',
        specialization: 'Medical Sciences',
        duration: 60,
    },
    {
        level: 'Doctorate',
        shortName: 'DM',
        name: 'Doctorate of Medicine',
        specialization: 'Cardiology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'DM',
        name: 'Doctorate of Medicine',
        specialization: 'Neurology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'DM',
        name: 'Doctorate of Medicine',
        specialization: 'Gastroenterology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'DM',
        name: 'Doctorate of Medicine',
        specialization: 'Nephrology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'DM',
        name: 'Doctorate of Medicine',
        specialization: 'Oncology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'MCh',
        name: 'Master of Chirurgiae',
        specialization: 'Neurosurgery',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'MCh',
        name: 'Master of Chirurgiae',
        specialization: 'Urology',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'MCh',
        name: 'Master of Chirurgiae',
        specialization: 'Plastic Surgery',
        duration: 36,
    },
    {
        level: 'Doctorate',
        shortName: 'MCh',
        name: 'Master of Chirurgiae',
        specialization: 'Cardiothoracic Surgery',
        duration: 36,
    },
];
